POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User1",
  "skill": 10.0,
  "latency": 50.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User2",
  "skill": 20.0,
  "latency": 60.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User3",
  "skill": 30.0,
  "latency": 70.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User4",
  "skill": 40.0,
  "latency": 80.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User5",
  "skill": 50.0,
  "latency": 90.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User6",
  "skill": 60.0,
  "latency": 100.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User7",
  "skill": 70.0,
  "latency": 110.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User8",
  "skill": 80.0,
  "latency": 120.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User9",
  "skill": 90.0,
  "latency": 130.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User10",
  "skill": 100.0,
  "latency": 140.0
}
###
POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User11",
  "skill": 95.0,
  "latency": 60.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User12",
  "skill": 85.0,
  "latency": 70.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User13",
  "skill": 75.0,
  "latency": 80.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User14",
  "skill": 65.0,
  "latency": 90.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User15",
  "skill": 55.0,
  "latency": 100.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User16",
  "skill": 45.0,
  "latency": 110.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User17",
  "skill": 35.0,
  "latency": 120.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User18",
  "skill": 25.0,
  "latency": 130.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User19",
  "skill": 15.0,
  "latency": 140.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User20",
  "skill": 5.0,
  "latency": 150.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User21",
  "skill": 40.0,
  "latency": 90.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User22",
  "skill": 43.0,
  "latency": 93.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User23",
  "skill": 46.0,
  "latency": 96.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User24",
  "skill": 49.0,
  "latency": 99.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User25",
  "skill": 52.0,
  "latency": 102.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User26",
  "skill": 55.0,
  "latency": 105.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User27",
  "skill": 58.0,
  "latency": 108.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User28",
  "skill": 61.0,
  "latency": 111.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User29",
  "skill": 64.0,
  "latency": 114.0
}
###

POST http://localhost:8080/users
Accept: */*
Content-Type: application/json

{
  "name": "User30",
  "skill": 67.0,
  "latency": 117.0
}
###
